/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiPerpus;

import java.awt.event.KeyEvent;
import static java.lang.System.err;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.sql.PreparedStatement;
import javax.swing.JFrame;

public class Jfram_kategory extends javax.swing.JFrame {

    DefaultTableModel tabelmodel;
    Connection con = null;
    Statement stat;
    ResultSet res;
    PreparedStatement pst = null;
    String kodee_rak = "";

    public Jfram_kategory() {
        initComponents();
        koneksi();
        datatojtable();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private void koneksi() {//begin
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/db_perpustakaan", "root", "");
            stat = con.createStatement();
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//end begin

    private void Aturkolom() {
        TableColumn column;
        jTable_user.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = jTable_user.getColumnModel().getColumn(0);
        column.setPreferredWidth(200);
        column = jTable_user.getColumnModel().getColumn(1);
        column.setPreferredWidth(265);
    }

    private void datatojtable() {
        DefaultTableModel tb = new DefaultTableModel();
        // Memberi nama pada setiap kolom tabel
        tb.addColumn("Kode Kategory");
        tb.addColumn("Nama Kategory");
        jTable_user.setModel(tb);
        try {
            // Mengambil data dari database
            res = stat.executeQuery("select *from tkategori");
            while (res.next()) {
                // Mengambil data dari database berdasarkan nama kolom pada tabel
                // Lalu di tampilkan ke dalam JTable
                tb.addRow(new Object[]{
                    res.getString("Id_kategori"),
                    res.getString("Nama_kategori")
                });
            }
            //Aturkolom(); //pemanggilan class untuk mengatur kolom
        } catch (SQLException e) {
        }
        Aturkolom();
    }//end method

    private void bersihkantextfiled() {
        kode_rak.setText("");
        nama_rak.setText("");
        kode_rak.requestFocus();
    }

    private void cekdatauser() {
        try {

            if (kode_rak.getText().length() != 8) {
                JOptionPane.showMessageDialog(null, "Panjang Karakter Kurang dari 8 Digit");
                kode_rak.requestFocus();
            } else {
                String sqlcek = "select *from tkategori where Id_kategori='" + kode_rak.getText() + "'";
                ResultSet rscek = stat.executeQuery(sqlcek);
                if (rscek.next()) {
                    nama_rak.setText(rscek.getString("Nama_kategori"));
                    nama_rak.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Kode Kategori Tidak Di temukan");
                    nama_rak.setText("");
                    nama_rak.requestFocus();
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "GAGAL KETEMU");
        }
    }//akhir Methor

    public void HapusData() {
        kodee_rak = (tabelmodel.getValueAt(jTable_user.getSelectedRow(), 0) + "");

        try {
            String sql = "delete from tkategori where Id_kategori='" + kodee_rak + "'";
            stat.executeUpdate(sql);

            kode_rak.requestFocus();
            
            kode_rak.setText("");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kode_rak = new javax.swing.JTextField();
        nama_rak = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_user = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setText("Kategori");

        jLabel2.setText("Nama Kategori");

        jLabel3.setText("Kode Kategori");

        kode_rak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_rakActionPerformed(evt);
            }
        });
        kode_rak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kode_rakKeyPressed(evt);
            }
        });

        nama_rak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nama_rakKeyPressed(evt);
            }
        });

        jTable_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_user);

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kode_rak, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(nama_rak))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(263, 263, 263))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btn_simpan)
                        .addGap(63, 63, 63)
                        .addComponent(btn_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_keluar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(116, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kode_rak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_rak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_hapus)
                    .addComponent(btn_keluar))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kode_rakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_rakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_rakActionPerformed

    private void kode_rakKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_rakKeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { // begin
            cekdatauser();
            //panggil komponen yang akan di tuju
        }  //end if
    }//GEN-LAST:event_kode_rakKeyPressed

    private void nama_rakKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nama_rakKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { // begin 
            btn_simpan.requestFocus();   //panggil komponen yang akan di tuju 
        }  //end if
    }//GEN-LAST:event_nama_rakKeyPressed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
       String kodeRak = kode_rak.getText().trim();
String namaRak = nama_rak.getText().trim();

// Validasi: Pastikan semua field terisi
if (kodeRak.length() != 8) {
    JOptionPane.showMessageDialog(null, "Kode Rak harus terdiri dari 8 karakter!",
            "Peringatan", JOptionPane.WARNING_MESSAGE);
    kode_rak.requestFocus();
    return;
}

if (kodeRak.isEmpty() || namaRak.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Kode Kategori atau Nama Kategori belum diisi. Harap lengkapi semua data!",
            "Peringatan", JOptionPane.WARNING_MESSAGE);
    kode_rak.requestFocus();
    return;
}

// Konfirmasi sebelum menyimpan atau mengupdate
int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menyimpan data?",
        "Konfirmasi", JOptionPane.YES_NO_OPTION);

if (confirm == JOptionPane.YES_OPTION) {
    try {
        PreparedStatement pstSelect = con.prepareStatement("SELECT * FROM tkategori WHERE Id_kategori = ?");
        pstSelect.setString(1, kodeRak);
        ResultSet rs = pstSelect.executeQuery();

        if (rs.next()) {
            // Jika Kode Rak sudah ada, beri opsi update sekali saja
            int confirmUpdate = JOptionPane.showConfirmDialog(null,
                    "Kode Rak sudah ada. Apakah Anda ingin memperbaruinya?",
                    "Peringatan", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (confirmUpdate == JOptionPane.YES_OPTION) {
                PreparedStatement pstUpdate = con.prepareStatement("UPDATE tkategori SET Nama_kategori = ? WHERE Id_kategori = ?");
                pstUpdate.setString(1, namaRak);
                pstUpdate.setString(2, kodeRak);
                pstUpdate.executeUpdate();
                pstUpdate.close();

                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!", "Update", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            // Jika belum ada, lakukan INSERT
            PreparedStatement pstInsert = con.prepareStatement("INSERT INTO tkategori (Id_kategori, Nama_kategori) VALUES (?, ?)");
            pstInsert.setString(1, kodeRak);
            pstInsert.setString(2, namaRak);
            pstInsert.executeUpdate();
            pstInsert.close();

            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!", "Insert", JOptionPane.INFORMATION_MESSAGE);
        }

        // Tutup koneksi
        rs.close();
        pstSelect.close();

        // Refresh tabel dan bersihkan input
        datatojtable();
        kode_rak.setText("");
        nama_rak.setText("");
        kode_rak.requestFocus();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data!\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        String kodeRak = kode_rak.getText().trim();

        if (kodeRak.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Konfirmasi sebelum menghapus
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                // Koneksi langsung di JFrame
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_perpustakaan", "root", "");

                // Query DELETE menggunakan PreparedStatement untuk keamanan
                String sql = "DELETE FROM tkategori WHERE Id_kategori = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, kodeRak);

                // Eksekusi query
                int rowsDeleted = pst.executeUpdate();
                pst.close();
                con.close();

                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus!", "Hapus", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
                }

                // Kosongkan JTextField setelah menghapus
                kode_rak.setText("");
                nama_rak.setText("");
                kode_rak.requestFocus();

                // Refresh tabel setelah perubahan
                datatojtable();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data!\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btn_hapusActionPerformed

    private void jTable_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_userMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        int selectedRow = jTable_user.getSelectedRow();
        kode_rak.setText(jTable_user.getValueAt(selectedRow, 0).toString());
//        txt_nama.setText(jTable_Rak.getValueAt(selectedRow, 1).toString());
        kodee_rak = jTable_user.getValueAt(selectedRow, 0).toString();
    }//GEN-LAST:event_jTable_userMouseClicked

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi keluar", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            dispose();

        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jfram_kategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jfram_kategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jfram_kategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jfram_kategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jfram_kategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_user;
    private javax.swing.JTextField kode_rak;
    private javax.swing.JTextField nama_rak;
    // End of variables declaration//GEN-END:variables
}
